import React from "react";
import Head from "next/head";
import { Section, Container, Main, Button } from "@/components";
import { useTheme } from "@/providers";
import styles from "./styles.module.scss";

export default function NotFound() {
  const { theme } = useTheme();
  const isDarkMode = theme === "dark-theme";

  return (
    <>
      <Head>
        <title>Not Found</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main withPadding>
        <Section
          className={`${styles.section} ${
            isDarkMode ? styles.darkMode : styles.lightMode
          }`}
        >
          <Container isFluid={false}>
            <h1 className={styles.title}>404</h1>
            <p className={styles.article}>
              The page you’re looking for doesn’t exist.
            </p>
            <Button className={styles.btn} withSvg variant="primary" href="/">
              Back to home
            </Button>
          </Container>
        </Section>
      </Main>
    </>
  );
}
